name: Build and Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm ci && yarn
      - name: Build Expo project
        run: npx expo build:android --no-wait
      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: expo-android-apk
          path: dist/*.apk
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.apk
          asset_name: expo-android.apk
          asset_content_type: application/vnd.android.package-archive