name: EAS Build and Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build --profile development --platform android --non-interactive --no-wait
      - name: Get build URL
        id: get_build_url
        run: |
          BUILD_URL=$(eas build:list --status=in-queue,in-progress,errored,finished --limit=1 --json | jq -r '.[0].artifacts.buildUrl')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          EXPO_BUILD_URL: ${{ env.BUILD_URL }}
        run: npx semantic-release
